# Site settings
title: Module CAO GEII
description: > # this means to ignore newlines until "baseurl:"
  Support des travaux pratiques de CAO à l'aide du logiciel Kicad du département GEII de l'IUT Lyon 1.
baseurl: "/cao-geii-lyon" # the subpath of your site, e.g. /blog/
url: "https://geiilyon.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

collections:
  collection_enonces:
    output: true
    permalink: /enonces/:name/
